name: Build

on:
  workflow_call:

jobs:
  # ----------------------------
  # Step 1: Prepare Environment
  # ----------------------------
  prepare:
    name: Prepare Node.js Environment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - name: Install Dependencies
        run: yarn --immutable

  # ----------------------------
  # Step 2: Build Project
  # ----------------------------
  build:
    name: Build Frontend Project
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - name: Build
        run: |
          yarn --immutable --immutable-cache
          yarn build
      - name: Require Clean Working Directory
        shell: bash
        run: |
          if ! git diff --exit-code; then
            echo "❌ Working tree dirty at end of build"
            exit 1
          fi